import { Suspense } from 'react'
import '../styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',

}

import localFont from 'next/font/local'

const pokemon = localFont({
  variable: '--font-pokemon',
  src: [
    {
      path: '../public/fonts/pokemon-solid.woff',
      weight: '400'
    }
  ]
})

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={`${pokemon.variable} font-sans`}>
        <Suspense fallback={<p>Loading...</p>}>
          {children}
        </Suspense>
      </body>
    </html>
  )
}
